import {z} from 'zod';

import {
  checkConnectionPrompt as googleCalendarCheckConnectionPrompt,
  startConnectionPrompt as googleCalendarStartConnectionPrompt,
  transferAgentPrompt as googleCalendarTransferAgentPrompt,
  createEventPrompt as googleCalendarCreateEventPrompt,
  deleteEventPrompt as googleCalendarDeleteEventPrompt,
  getCalendarPrompt as googleCalendarGetCalendarPrompt,
  getEventPrompt as googleCalendarGetEventPrompt,
  listCalendarsPrompt as googleCalendarListCalendarsPrompt,
  listEventsPrompt as googleCalendarListEventsPrompt,
  updateEventPrompt as googleCalendarUpdateEventPrompt,
} from './prompts/google-calendar';
import {
  checkConnectionPrompt as googleDocsCheckConnectionPrompt,
  startConnectionPrompt as googleDocsStartConnectionPrompt,
  transferAgentPrompt as googleDocsTransferAgentPrompt,
  appendTextPrompt as googleDocsAppendTextPrompt,
  createDocumentPrompt as googleDocsCreateDocumentPrompt,
  findDocumentPrompt as googleDocsFindDocumentPrompt,
  getDocumentPrompt as googleDocsGetDocumentPrompt,
} from './prompts/google-docs';
import {
  checkConnectionPrompt as googleDriveCheckConnectionPrompt,
  startConnectionPrompt as googleDriveStartConnectionPrompt,
  transferAgentPrompt as googleDriveTransferAgentPrompt,
  createFilePrompt as googleDriveCreateFilePrompt,
  createFolderPrompt as googleDriveCreateFolderPrompt,
  deleteFilePrompt as googleDriveDeleteFilePrompt,
  findFilePrompt as googleDriveFindFilePrompt,
  findFolderPrompt as googleDriveFindFolderPrompt,
  getFilePrompt as googleDriveGetFilePrompt,
  listFilesPrompt as googleDriveListFilesPrompt,
} from './prompts/google-drive';
import {
  checkConnectionPrompt as googleMailCheckConnectionPrompt,
  startConnectionPrompt as googleMailStartConnectionPrompt,
  transferAgentPrompt as googleMailTransferAgentPrompt,
  addLabelToEmailPrompt as googleMailAddLabelToEmailPrompt,
  createDraftPrompt as googleMailCreateDraftPrompt,
  findEmailPrompt as googleMailFindEmailPrompt,
  listLabelsPrompt as googleMailListLabelsPrompt,
  sendEmailPrompt as googleMailSendEmailPrompt,
} from './prompts/google-mail';
import {
  checkConnectionPrompt as googleSheetCheckConnectionPrompt,
  startConnectionPrompt as googleSheetStartConnectionPrompt,
  transferAgentPrompt as googleSheetTransferAgentPrompt,
  addColumnPrompt as googleSheetAddColumnPrompt,
  addMultipleRowsPrompt as googleSheetAddMultipleRowsPrompt,
  clearCellPrompt as googleSheetClearCellPrompt,
  clearRowsPrompt as googleSheetClearRowsPrompt,
  createSpreadsheetPrompt as googleSheetCreateSpreadsheetPrompt,
  createWorksheetPrompt as googleSheetCreateWorksheetPrompt,
  deleteRowsPrompt as googleSheetDeleteRowsPrompt,
  deleteWorksheetPrompt as googleSheetDeleteWorksheetPrompt,
  findRowPrompt as googleSheetFindRowPrompt,
  getCellPrompt as googleSheetGetCellPrompt,
  getSpreadsheetPrompt as googleSheetGetSpreadsheetPrompt,
  getValuesInRangePrompt as googleSheetGetValuesInRangePrompt,
  listWorksheetsPrompt as googleSheetListWorksheetsPrompt,
  updateCellPrompt as googleSheetUpdateCellPrompt,
  updateMultipleRowsPrompt as googleSheetUpdateMultipleRowsPrompt,
  updateRowPrompt as googleSheetUpdateRowPrompt,
} from './prompts/google-sheet';
import {
  checkConnectionPrompt as hubspotCheckConnectionPrompt,
  startConnectionPrompt as hubspotStartConnectionPrompt,
  transferAgentPrompt as hubspotTransferAgentPrompt,
  createContactPrompt as hubspotCreateContactPrompt,
  getContactPrompt as hubspotGetContactPrompt,
  listContactsPrompt as hubspotListContactsPrompt,
  searchContactsPrompt as hubspotSearchContactsPrompt,
  mergeContactsPrompt as hubspotMergeContactsPrompt,
  updateContactPrompt as hubspotUpdateContactPrompt,
  deleteContactPrompt as hubspotDeleteContactPrompt,
  createDealPrompt as hubspotCreateDealPrompt,
  getDealPrompt as hubspotGetDealPrompt,
  listDealsPrompt as hubspotListDealsPrompt,
  searchDealsPrompt as hubspotSearchDealsPrompt,
  mergeDealPrompt as hubspotMergeDealPrompt,
  updateDealPrompt as hubspotUpdateDealPrompt,
  deleteDealPrompt as hubspotDeleteDealPrompt,
} from './prompts/hubspot';
import {
  checkConnectionPrompt as jiraCheckConnectionPrompt,
  startConnectionPrompt as jiraStartConnectionPrompt,
  transferAgentPrompt as jiraTransferAgentPrompt,
  listCloudsPrompt as jiraListCloudsPrompt,
  getIssuePrompt as jiraGetIssuePrompt,
  listIssuesPrompt as jiraListIssuesPrompt,
  addCommentToIssuePrompt as jiraAddCommentToIssuePrompt,
  listCommentsPrompt as jiraListCommentsPrompt,
  updateCommentPrompt as jiraUpdateCommentPrompt,
  listProjectsPrompt as jiraListProjectsPrompt,
  getUserPrompt as jiraGetUserPrompt,
  listUsersPrompt as jiraListUsersPrompt,
} from './prompts/jira';
import {
  checkConnectionPrompt as klaviyoCheckConnectionPrompt,
  startConnectionPrompt as klaviyoStartConnectionPrompt,
  transferAgentPrompt as klaviyoTransferAgentPrompt,
  addProfilesToListPrompt as klaviyoAddProfilesToListPrompt,
  assignTemplateToCampaignMessagePrompt as klaviyoAssignTemplateToCampaignMessagePrompt,
  createCampaignPrompt as klaviyoCreateCampaignPrompt,
  createListPrompt as klaviyoCreateListPrompt,
  createProfilePrompt as klaviyoCreateProfilePrompt,
  createTemplatePrompt as klaviyoCreateTemplatePrompt,
  getCampaignMessagesPrompt as klaviyoGetCampaignMessagesPrompt,
  getCampaignSendJobPrompt as klaviyoGetCampaignSendJobPrompt,
  getCampaignsPrompt as klaviyoGetCampaignsPrompt,
  getListsPrompt as klaviyoGetListsPrompt,
  getProfilesForListPrompt as klaviyoGetProfilesForListPrompt,
  getProfilesPrompt as klaviyoGetProfilesPrompt,
  getTemplatesPrompt as klaviyoGetTemplatesPrompt,
  sendCampaignPrompt as klaviyoSendCampaignPrompt,
} from './prompts/klaviyo';
import {
  checkConnectionPrompt as salesforceCheckConnectionPrompt,
  startConnectionPrompt as salesforceStartConnectionPrompt,
  transferAgentPrompt as salesforceTransferAgentPrompt,
  createContactPrompt as salesforceCreateContactPrompt,
  getContactPrompt as salesforceGetContactPrompt,
  listContactsPrompt as salesforceListContactsPrompt,
} from './prompts/salesforce';

import {
  checkConnectionParameters as googleCalendarCheckConnectionParameters,
  startConnectionParameters as googleCalendarStartConnectionParameters,
  transferAgentParameters as googleCalendarTransferAgentParameters,
  createEventParameters as googleCalendarCreateEventParameters,
  deleteEventParameters as googleCalendarDeleteEventParameters,
  getCalendarParameters as googleCalendarGetCalendarParameters,
  getEventParameters as googleCalendarGetEventParameters,
  listCalendarsParameters as googleCalendarListCalendarsParameters,
  listEventsParameters as googleCalendarListEventsParameters,
  updateEventParameters as googleCalendarUpdateEventParameters,
} from './parameters/google-calendar';
import {
  checkConnectionParameters as googleDocsCheckConnectionParameters,
  startConnectionParameters as googleDocsStartConnectionParameters,
  transferAgentParameters as googleDocsTransferAgentParameters,
  appendTextParameters as googleDocsAppendTextParameters,
  createDocumentParameters as googleDocsCreateDocumentParameters,
  findDocumentParameters as googleDocsFindDocumentParameters,
  getDocumentParameters as googleDocsGetDocumentParameters,
} from './parameters/google-docs';
import {
  checkConnectionParameters as googleDriveCheckConnectionParameters,
  startConnectionParameters as googleDriveStartConnectionParameters,
  transferAgentParameters as googleDriveTransferAgentParameters,
  createFileParameters as googleDriveCreateFileParameters,
  createFolderParameters as googleDriveCreateFolderParameters,
  deleteFileParameters as googleDriveDeleteFileParameters,
  findFileParameters as googleDriveFindFileParameters,
  findFolderParameters as googleDriveFindFolderParameters,
  getFileParameters as googleDriveGetFileParameters,
  listFilesParameters as googleDriveListFilesParameters,
} from './parameters/google-drive';
import {
  checkConnectionParameters as googleMailCheckConnectionParameters,
  startConnectionParameters as googleMailStartConnectionParameters,
  transferAgentParameters as googleMailTransferAgentParameters,
  addLabelToEmailParameters as googleMailAddLabelToEmailParameters,
  createDraftParameters as googleMailCreateDraftParameters,
  findEmailParameters as googleMailFindEmailParameters,
  listLabelsParameters as googleMailListLabelsParameters,
  sendEmailParameters as googleMailSendEmailParameters,
} from './parameters/google-mail';
import {
  checkConnectionParameters as googleSheetCheckConnectionParameters,
  startConnectionParameters as googleSheetStartConnectionParameters,
  transferAgentParameters as googleSheetTransferAgentParameters,
  addColumnParameters as googleSheetAddColumnParameters,
  addMultipleRowsParameters as googleSheetAddMultipleRowsParameters,
  clearCellParameters as googleSheetClearCellParameters,
  clearRowsParameters as googleSheetClearRowsParameters,
  createSpreadsheetParameters as googleSheetCreateSpreadsheetParameters,
  createWorksheetParameters as googleSheetCreateWorksheetParameters,
  deleteRowsParameters as googleSheetDeleteRowsParameters,
  deleteWorksheetParameters as googleSheetDeleteWorksheetParameters,
  findRowParameters as googleSheetFindRowParameters,
  getCellParameters as googleSheetGetCellParameters,
  getSpreadsheetParameters as googleSheetGetSpreadsheetParameters,
  getValuesInRangeParameters as googleSheetGetValuesInRangeParameters,
  listWorksheetsParameters as googleSheetListWorksheetsParameters,
  updateCellParameters as googleSheetUpdateCellParameters,
  updateMultipleRowsParameters as googleSheetUpdateMultipleRowsParameters,
  updateRowParameters as googleSheetUpdateRowParameters,
} from './parameters/google-sheet';
import {
  checkConnectionParameters as hubspotCheckConnectionParameters,
  startConnectionParameters as hubspotStartConnectionParameters,
  transferAgentParameters as hubspotTransferAgentParameters,
  createContactParameters as hubspotCreateContactParameters,
  getContactParameters as hubspotGetContactParameters,
  listContactsParameters as hubspotListContactsParameters,
  searchContactsParameters as hubspotSearchContactsParameters,
  mergeContactsParameters as hubspotMergeContactsParameters,
  updateContactParameters as hubspotUpdateContactParameters,
  deleteContactParameters as hubspotDeleteContactParameters,
  createDealParameters as hubspotCreateDealParameters,
  getDealParameters as hubspotGetDealParameters,
  listDealsParameters as hubspotListDealsParameters,
  searchDealsParameters as hubspotSearchDealsParameters,
  mergeDealParameters as hubspotMergeDealParameters,
  updateDealParameters as hubspotUpdateDealParameters,
  deleteDealParameters as hubspotDeleteDealParameters,
} from './parameters/hubspot';
import {
  checkConnectionParameters as jiraCheckConnectionParameters,
  startConnectionParameters as jiraStartConnectionParameters,
  transferAgentParameters as jiraTransferAgentParameters,
  listCloudsParameters as jiraListCloudsParameters,
  getIssueParameters as jiraGetIssueParameters,
  listIssuesParameters as jiraListIssuesParameters,
  addCommentToIssueParameters as jiraAddCommentToIssueParameters,
  listCommentsParameters as jiraListCommentsParameters,
  updateCommentParameters as jiraUpdateCommentParameters,
  listProjectsParameters as jiraListProjectsParameters,
  getUserParameters as jiraGetUserParameters,
  listUsersParameters as jiraListUsersParameters,
} from './parameters/jira';
import {
  checkConnectionParameters as klaviyoCheckConnectionParameters,
  startConnectionParameters as klaviyoStartConnectionParameters,
  transferAgentParameters as klaviyoTransferAgentParameters,
  addProfilesToListParameters as klaviyoAddProfilesToListParameters,
  assignTemplateToCampaignMessageParameters as klaviyoAssignTemplateToCampaignMessageParameters,
  createCampaignParameters as klaviyoCreateCampaignParameters,
  createListParameters as klaviyoCreateListParameters,
  createProfileParameters as klaviyoCreateProfileParameters,
  createTemplateParameters as klaviyoCreateTemplateParameters,
  getCampaignMessagesParameters as klaviyoGetCampaignMessagesParameters,
  getCampaignSendJobParameters as klaviyoGetCampaignSendJobParameters,
  getCampaignsParameters as klaviyoGetCampaignsParameters,
  getListsParameters as klaviyoGetListsParameters,
  getProfilesForListParameters as klaviyoGetProfilesForListParameters,
  getProfilesParameters as klaviyoGetProfilesParameters,
  getTemplatesParameters as klaviyoGetTemplatesParameters,
  sendCampaignParameters as klaviyoSendCampaignParameters,
} from './parameters/klaviyo';
import {
  checkConnectionParameters as salesforceCheckConnectionParameters,
  startConnectionParameters as salesforceStartConnectionParameters,
  transferAgentParameters as salesforceTransferAgentParameters,
  createContactParameters as salesforceCreateContactParameters,
  getContactParameters as salesforceGetContactParameters,
  listContactsParameters as salesforceListContactsParameters,
} from './parameters/salesforce';

export type Tool = {
  method: string;
  name: string;
  description: string;
  parameters: z.ZodObject<any, any, any, any>;
  actions: {
    [key: string]: {
      [action: string]: boolean;
    };
  };
};

const tools: Tool[] = [
  {
    method: 'google-calendar_check_connection',
    name: 'Google Calendar Check Connection',
    description: googleCalendarCheckConnectionPrompt,
    parameters: googleCalendarCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'google-calendar_start_connection',
    name: 'Google Calendar Start Connection',
    description: googleCalendarStartConnectionPrompt,
    parameters: googleCalendarStartConnectionParameters,
    actions: {},
  },
  {
    method: 'google-calendar_transfer_agent',
    name: 'Google Calendar Transfer Agent',
    description: googleCalendarTransferAgentPrompt,
    parameters: googleCalendarTransferAgentParameters,
    actions: {},
  },
  {
    method: 'google-calendar_create_event',
    name: 'Google Calendar Create Event',
    description: googleCalendarCreateEventPrompt,
    parameters: googleCalendarCreateEventParameters,
    actions: {},
  },
  {
    method: 'google-calendar_delete_event',
    name: 'Google Calendar Delete Event',
    description: googleCalendarDeleteEventPrompt,
    parameters: googleCalendarDeleteEventParameters,
    actions: {},
  },
  {
    method: 'google-calendar_get_calendar',
    name: 'Google Calendar Get Calendar',
    description: googleCalendarGetCalendarPrompt,
    parameters: googleCalendarGetCalendarParameters,
    actions: {},
  },
  {
    method: 'google-calendar_get_event',
    name: 'Google Calendar Get Event',
    description: googleCalendarGetEventPrompt,
    parameters: googleCalendarGetEventParameters,
    actions: {},
  },
  {
    method: 'google-calendar_list_calendars',
    name: 'Google Calendar List Calendars',
    description: googleCalendarListCalendarsPrompt,
    parameters: googleCalendarListCalendarsParameters,
    actions: {},
  },
  {
    method: 'google-calendar_list_events',
    name: 'Google Calendar List Events',
    description: googleCalendarListEventsPrompt,
    parameters: googleCalendarListEventsParameters,
    actions: {},
  },
  {
    method: 'google-calendar_update_event',
    name: 'Google Calendar Update Event',
    description: googleCalendarUpdateEventPrompt,
    parameters: googleCalendarUpdateEventParameters,
    actions: {},
  },
  {
    method: 'google-docs_check_connection',
    name: 'Google Docs Check Connection',
    description: googleDocsCheckConnectionPrompt,
    parameters: googleDocsCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'google-docs_start_connection',
    name: 'Google Docs Start Connection',
    description: googleDocsStartConnectionPrompt,
    parameters: googleDocsStartConnectionParameters,
    actions: {},
  },
  {
    method: 'google-docs_transfer_agent',
    name: 'Google Docs Transfer Agent',
    description: googleDocsTransferAgentPrompt,
    parameters: googleDocsTransferAgentParameters,
    actions: {},
  },
  {
    method: 'google-docs_append_text',
    name: 'Google Docs Append Text',
    description: googleDocsAppendTextPrompt,
    parameters: googleDocsAppendTextParameters,
    actions: {},
  },
  {
    method: 'google-docs_create_document',
    name: 'Google Docs Create Document',
    description: googleDocsCreateDocumentPrompt,
    parameters: googleDocsCreateDocumentParameters,
    actions: {},
  },
  {
    method: 'google-docs_find_document',
    name: 'Google Docs Find Document',
    description: googleDocsFindDocumentPrompt,
    parameters: googleDocsFindDocumentParameters,
    actions: {},
  },
  {
    method: 'google-docs_get_document',
    name: 'Google Docs Get Document',
    description: googleDocsGetDocumentPrompt,
    parameters: googleDocsGetDocumentParameters,
    actions: {},
  },
  {
    method: 'google-drive_check_connection',
    name: 'Google Drive Check Connection',
    description: googleDriveCheckConnectionPrompt,
    parameters: googleDriveCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'google-drive_start_connection',
    name: 'Google Drive Start Connection',
    description: googleDriveStartConnectionPrompt,
    parameters: googleDriveStartConnectionParameters,
    actions: {},
  },
  {
    method: 'google-drive_transfer_agent',
    name: 'Google Drive Transfer Agent',
    description: googleDriveTransferAgentPrompt,
    parameters: googleDriveTransferAgentParameters,
    actions: {},
  },
  {
    method: 'google-drive_create_file',
    name: 'Google Drive Create File',
    description: googleDriveCreateFilePrompt,
    parameters: googleDriveCreateFileParameters,
    actions: {},
  },
  {
    method: 'google-drive_create_folder',
    name: 'Google Drive Create Folder',
    description: googleDriveCreateFolderPrompt,
    parameters: googleDriveCreateFolderParameters,
    actions: {},
  },
  {
    method: 'google-drive_delete_file',
    name: 'Google Drive Delete File',
    description: googleDriveDeleteFilePrompt,
    parameters: googleDriveDeleteFileParameters,
    actions: {},
  },
  {
    method: 'google-drive_find_file',
    name: 'Google Drive Find File',
    description: googleDriveFindFilePrompt,
    parameters: googleDriveFindFileParameters,
    actions: {},
  },
  {
    method: 'google-drive_find_folder',
    name: 'Google Drive Find Folder',
    description: googleDriveFindFolderPrompt,
    parameters: googleDriveFindFolderParameters,
    actions: {},
  },
  {
    method: 'google-drive_get_file',
    name: 'Google Drive Get File',
    description: googleDriveGetFilePrompt,
    parameters: googleDriveGetFileParameters,
    actions: {},
  },
  {
    method: 'google-drive_list_files',
    name: 'Google Drive List Files',
    description: googleDriveListFilesPrompt,
    parameters: googleDriveListFilesParameters,
    actions: {},
  },
  {
    method: 'google-mail_check_connection',
    name: 'Gmail Check Connection',
    description: googleMailCheckConnectionPrompt,
    parameters: googleMailCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'google-mail_start_connection',
    name: 'Gmail Start Connection',
    description: googleMailStartConnectionPrompt,
    parameters: googleMailStartConnectionParameters,
    actions: {},
  },
  {
    method: 'google-mail_transfer_agent',
    name: 'Gmail Transfer Agent',
    description: googleMailTransferAgentPrompt,
    parameters: googleMailTransferAgentParameters,
    actions: {},
  },
  {
    method: 'google-mail_add_label_to_email',
    name: 'Gmail Add Label to Email',
    description: googleMailAddLabelToEmailPrompt,
    parameters: googleMailAddLabelToEmailParameters,
    actions: {},
  },
  {
    method: 'google-mail_create_draft',
    name: 'Gmail Create Draft',
    description: googleMailCreateDraftPrompt,
    parameters: googleMailCreateDraftParameters,
    actions: {},
  },
  {
    method: 'google-mail_find_email',
    name: 'Gmail Find Email',
    description: googleMailFindEmailPrompt,
    parameters: googleMailFindEmailParameters,
    actions: {},
  },
  {
    method: 'google-mail_list_labels',
    name: 'Gmail List Labels',
    description: googleMailListLabelsPrompt,
    parameters: googleMailListLabelsParameters,
    actions: {},
  },
  {
    method: 'google-mail_send_email',
    name: 'Gmail Send Email',
    description: googleMailSendEmailPrompt,
    parameters: googleMailSendEmailParameters,
    actions: {},
  },
  {
    method: 'google-sheet_check_connection',
    name: 'Google Sheets Check Connection',
    description: googleSheetCheckConnectionPrompt,
    parameters: googleSheetCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'google-sheet_start_connection',
    name: 'Google Sheets Start Connection',
    description: googleSheetStartConnectionPrompt,
    parameters: googleSheetStartConnectionParameters,
    actions: {},
  },
  {
    method: 'google-sheet_transfer_agent',
    name: 'Google Sheets Transfer Agent',
    description: googleSheetTransferAgentPrompt,
    parameters: googleSheetTransferAgentParameters,
    actions: {},
  },
  {
    method: 'google-sheet_add_column',
    name: 'Google Sheets Add Column',
    description: googleSheetAddColumnPrompt,
    parameters: googleSheetAddColumnParameters,
    actions: {},
  },
  {
    method: 'google-sheet_add_multiple_rows',
    name: 'Google Sheets Add Multiple Rows',
    description: googleSheetAddMultipleRowsPrompt,
    parameters: googleSheetAddMultipleRowsParameters,
    actions: {},
  },
  {
    method: 'google-sheet_clear_cell',
    name: 'Google Sheets Clear Cell',
    description: googleSheetClearCellPrompt,
    parameters: googleSheetClearCellParameters,
    actions: {},
  },
  {
    method: 'google-sheet_clear_rows',
    name: 'Google Sheets Clear Rows',
    description: googleSheetClearRowsPrompt,
    parameters: googleSheetClearRowsParameters,
    actions: {},
  },
  {
    method: 'google-sheet_create_spreadsheet',
    name: 'Google Sheets Create Spreadsheet',
    description: googleSheetCreateSpreadsheetPrompt,
    parameters: googleSheetCreateSpreadsheetParameters,
    actions: {},
  },
  {
    method: 'google-sheet_create_worksheet',
    name: 'Google Sheets Create Worksheet',
    description: googleSheetCreateWorksheetPrompt,
    parameters: googleSheetCreateWorksheetParameters,
    actions: {},
  },
  {
    method: 'google-sheet_delete_rows',
    name: 'Google Sheets Delete Rows',
    description: googleSheetDeleteRowsPrompt,
    parameters: googleSheetDeleteRowsParameters,
    actions: {},
  },
  {
    method: 'google-sheet_delete_worksheet',
    name: 'Google Sheets Delete Worksheet',
    description: googleSheetDeleteWorksheetPrompt,
    parameters: googleSheetDeleteWorksheetParameters,
    actions: {},
  },
  {
    method: 'google-sheet_find_row',
    name: 'Google Sheets Find Row',
    description: googleSheetFindRowPrompt,
    parameters: googleSheetFindRowParameters,
    actions: {},
  },
  {
    method: 'google-sheet_get_cell',
    name: 'Google Sheets Get Cell',
    description: googleSheetGetCellPrompt,
    parameters: googleSheetGetCellParameters,
    actions: {},
  },
  {
    method: 'google-sheet_get_spreadsheet',
    name: 'Google Sheets Get Spreadsheet',
    description: googleSheetGetSpreadsheetPrompt,
    parameters: googleSheetGetSpreadsheetParameters,
    actions: {},
  },
  {
    method: 'google-sheet_get_values_in_range',
    name: 'Google Sheets Get Values in Range',
    description: googleSheetGetValuesInRangePrompt,
    parameters: googleSheetGetValuesInRangeParameters,
    actions: {},
  },
  {
    method: 'google-sheet_list_worksheets',
    name: 'Google Sheets List Worksheets',
    description: googleSheetListWorksheetsPrompt,
    parameters: googleSheetListWorksheetsParameters,
    actions: {},
  },
  {
    method: 'google-sheet_update_cell',
    name: 'Google Sheets Update Cell',
    description: googleSheetUpdateCellPrompt,
    parameters: googleSheetUpdateCellParameters,
    actions: {},
  },
  {
    method: 'google-sheet_update_multiple_rows',
    name: 'Google Sheets Update Multiple Rows',
    description: googleSheetUpdateMultipleRowsPrompt,
    parameters: googleSheetUpdateMultipleRowsParameters,
    actions: {},
  },
  {
    method: 'google-sheet_update_row',
    name: 'Google Sheets Update Row',
    description: googleSheetUpdateRowPrompt,
    parameters: googleSheetUpdateRowParameters,
    actions: {},
  },
  {
    method: 'hubspot_check_connection',
    name: 'HubSpot Check Connection',
    description: hubspotCheckConnectionPrompt,
    parameters: hubspotCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'hubspot_start_connection',
    name: 'HubSpot Start Connection',
    description: hubspotStartConnectionPrompt,
    parameters: hubspotStartConnectionParameters,
    actions: {},
  },
  {
    method: 'hubspot_transfer_agent',
    name: 'HubSpot Transfer Agent',
    description: hubspotTransferAgentPrompt,
    parameters: hubspotTransferAgentParameters,
    actions: {},
  },
  {
    method: 'hubspot_create_contact',
    name: 'HubSpot Create Contact',
    description: hubspotCreateContactPrompt,
    parameters: hubspotCreateContactParameters,
    actions: {},
  },
  {
    method: 'hubspot_get_contact',
    name: 'HubSpot Get Contact',
    description: hubspotGetContactPrompt,
    parameters: hubspotGetContactParameters,
    actions: {},
  },
  {
    method: 'hubspot_list_contacts',
    name: 'HubSpot List Contacts',
    description: hubspotListContactsPrompt,
    parameters: hubspotListContactsParameters,
    actions: {},
  },
  {
    method: 'hubspot_search_contacts',
    name: 'HubSpot Search Contacts',
    description: hubspotSearchContactsPrompt,
    parameters: hubspotSearchContactsParameters,
    actions: {},
  },
  {
    method: 'hubspot_merge_contacts',
    name: 'HubSpot Merge Contacts',
    description: hubspotMergeContactsPrompt,
    parameters: hubspotMergeContactsParameters,
    actions: {},
  },
  {
    method: 'hubspot_update_contact',
    name: 'HubSpot Update Contact',
    description: hubspotUpdateContactPrompt,
    parameters: hubspotUpdateContactParameters,
    actions: {},
  },
  {
    method: 'hubspot_delete_contact',
    name: 'HubSpot Delete Contact',
    description: hubspotDeleteContactPrompt,
    parameters: hubspotDeleteContactParameters,
    actions: {},
  },
  {
    method: 'hubspot_create_deal',
    name: 'HubSpot Create Deal',
    description: hubspotCreateDealPrompt,
    parameters: hubspotCreateDealParameters,
    actions: {},
  },
  {
    method: 'hubspot_get_deal',
    name: 'HubSpot Get Deal',
    description: hubspotGetDealPrompt,
    parameters: hubspotGetDealParameters,
    actions: {},
  },
  {
    method: 'hubspot_list_deals',
    name: 'HubSpot List Deals',
    description: hubspotListDealsPrompt,
    parameters: hubspotListDealsParameters,
    actions: {},
  },
  {
    method: 'hubspot_search_deals',
    name: 'HubSpot Search Deals',
    description: hubspotSearchDealsPrompt,
    parameters: hubspotSearchDealsParameters,
    actions: {},
  },
  {
    method: 'hubspot_merge_deals',
    name: 'HubSpot Merge Deals',
    description: hubspotMergeDealPrompt,
    parameters: hubspotMergeDealParameters,
    actions: {},
  },
  {
    method: 'hubspot_update_deal',
    name: 'HubSpot Update Deal',
    description: hubspotUpdateDealPrompt,
    parameters: hubspotUpdateDealParameters,
    actions: {},
  },
  {
    method: 'hubspot_delete_deal',
    name: 'HubSpot Delete Deal',
    description: hubspotDeleteDealPrompt,
    parameters: hubspotDeleteDealParameters,
    actions: {},
  },
  {
    method: 'salesforce_check_connection',
    name: 'Salesforce Check Connection',
    description: salesforceCheckConnectionPrompt,
    parameters: salesforceCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'salesforce_start_connection',
    name: 'Salesforce Start Connection',
    description: salesforceStartConnectionPrompt,
    parameters: salesforceStartConnectionParameters,
    actions: {},
  },
  {
    method: 'salesforce_transfer_agent',
    name: 'Salesforce Transfer Agent',
    description: salesforceTransferAgentPrompt,
    parameters: salesforceTransferAgentParameters,
    actions: {},
  },
  {
    method: 'salesforce_create_contact',
    name: 'Salesforce Create Contact',
    description: salesforceCreateContactPrompt,
    parameters: salesforceCreateContactParameters,
    actions: {},
  },
  {
    method: 'salesforce_get_contact',
    name: 'Salesforce Get Contact',
    description: salesforceGetContactPrompt,
    parameters: salesforceGetContactParameters,
    actions: {},
  },
  {
    method: 'salesforce_list_contacts',
    name: 'Salesforce List Contacts',
    description: salesforceListContactsPrompt,
    parameters: salesforceListContactsParameters,
    actions: {},
  },
  {
    method: 'klaviyo_check_connection',
    name: 'Klaviyo Check Connection',
    description: klaviyoCheckConnectionPrompt,
    parameters: klaviyoCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'klaviyo_start_connection',
    name: 'Klaviyo Start Connection',
    description: klaviyoStartConnectionPrompt,
    parameters: klaviyoStartConnectionParameters,
    actions: {},
  },
  {
    method: 'klaviyo_transfer_agent',
    name: 'Klaviyo Transfer Agent',
    description: klaviyoTransferAgentPrompt,
    parameters: klaviyoTransferAgentParameters,
    actions: {},
  },
  {
    method: 'klaviyo_add_profiles_to_list',
    name: 'Klaviyo Add Profiles to List',
    description: klaviyoAddProfilesToListPrompt,
    parameters: klaviyoAddProfilesToListParameters,
    actions: {},
  },
  {
    method: 'klaviyo_assign_template_to_campaign_message',
    name: 'Klaviyo Assign Template to Campaign Message',
    description: klaviyoAssignTemplateToCampaignMessagePrompt,
    parameters: klaviyoAssignTemplateToCampaignMessageParameters,
    actions: {},
  },
  {
    method: 'klaviyo_create_campaign',
    name: 'Klaviyo Create Campaign',
    description: klaviyoCreateCampaignPrompt,
    parameters: klaviyoCreateCampaignParameters,
    actions: {},
  },
  {
    method: 'klaviyo_create_list',
    name: 'Klaviyo Create List',
    description: klaviyoCreateListPrompt,
    parameters: klaviyoCreateListParameters,
    actions: {},
  },
  {
    method: 'klaviyo_create_profile',
    name: 'Klaviyo Create Profile',
    description: klaviyoCreateProfilePrompt,
    parameters: klaviyoCreateProfileParameters,
    actions: {},
  },
  {
    method: 'klaviyo_create_template',
    name: 'Klaviyo Create Template',
    description: klaviyoCreateTemplatePrompt,
    parameters: klaviyoCreateTemplateParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_campaign_messages',
    name: 'Klaviyo Get Campaign Messages',
    description: klaviyoGetCampaignMessagesPrompt,
    parameters: klaviyoGetCampaignMessagesParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_campaign_send_job',
    name: 'Klaviyo Get Campaign Send Job',
    description: klaviyoGetCampaignSendJobPrompt,
    parameters: klaviyoGetCampaignSendJobParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_campaigns',
    name: 'Klaviyo Get Campaigns',
    description: klaviyoGetCampaignsPrompt,
    parameters: klaviyoGetCampaignsParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_lists',
    name: 'Klaviyo Get Lists',
    description: klaviyoGetListsPrompt,
    parameters: klaviyoGetListsParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_profiles_for_list',
    name: 'Klaviyo Get Profiles for List',
    description: klaviyoGetProfilesForListPrompt,
    parameters: klaviyoGetProfilesForListParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_profiles',
    name: 'Klaviyo Get Profiles',
    description: klaviyoGetProfilesPrompt,
    parameters: klaviyoGetProfilesParameters,
    actions: {},
  },
  {
    method: 'klaviyo_get_templates',
    name: 'Klaviyo Get Templates',
    description: klaviyoGetTemplatesPrompt,
    parameters: klaviyoGetTemplatesParameters,
    actions: {},
  },
  {
    method: 'klaviyo_send_campaign',
    name: 'Klaviyo Send Campaign',
    description: klaviyoSendCampaignPrompt,
    parameters: klaviyoSendCampaignParameters,
    actions: {},
  },
  {
    method: 'jira_check_connection',
    name: 'Jira Check Connection',
    description: jiraCheckConnectionPrompt,
    parameters: jiraCheckConnectionParameters,
    actions: {},
  },
  {
    method: 'jira_start_connection',
    name: 'Jira Start Connection',
    description: jiraStartConnectionPrompt,
    parameters: jiraStartConnectionParameters,
    actions: {},
  },
  {
    method: 'jira_transfer_agent',
    name: 'Jira Transfer Agent',
    description: jiraTransferAgentPrompt,
    parameters: jiraTransferAgentParameters,
    actions: {},
  },
  {
    method: 'jira_list_clouds',
    name: 'Jira List Clouds',
    description: jiraListCloudsPrompt,
    parameters: jiraListCloudsParameters,
    actions: {},
  },
  {
    method: 'jira_get_issue',
    name: 'Jira Get Issue',
    description: jiraGetIssuePrompt,
    parameters: jiraGetIssueParameters,
    actions: {},
  },
  {
    method: 'jira_list_issues',
    name: 'Jira List Issues',
    description: jiraListIssuesPrompt,
    parameters: jiraListIssuesParameters,
    actions: {},
  },
  {
    method: 'jira_add_comment_to_issue',
    name: 'Jira Add Comment to Issue',
    description: jiraAddCommentToIssuePrompt,
    parameters: jiraAddCommentToIssueParameters,
    actions: {},
  },
  {
    method: 'jira_list_comments',
    name: 'Jira List Comments',
    description: jiraListCommentsPrompt,
    parameters: jiraListCommentsParameters,
    actions: {},
  },
  {
    method: 'jira_update_comment',
    name: 'Jira Update Comment',
    description: jiraUpdateCommentPrompt,
    parameters: jiraUpdateCommentParameters,
    actions: {},
  },
  {
    method: 'jira_list_projects',
    name: 'Jira List Projects',
    description: jiraListProjectsPrompt,
    parameters: jiraListProjectsParameters,
    actions: {},
  },
  {
    method: 'jira_get_user',
    name: 'Jira Get User',
    description: jiraGetUserPrompt,
    parameters: jiraGetUserParameters,
    actions: {},
  },
  {
    method: 'jira_list_users',
    name: 'Jira List Users',
    description: jiraListUsersPrompt,
    parameters: jiraListUsersParameters,
    actions: {},
  },
];

export default tools;
