name: Release

on:
  workflow_dispatch: {}

jobs:
  npm-release:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm

    defaults:
      run:
        working-directory: ./tools/modelcontextprotocol

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  agent-toolkit-npm-release:
    name: Publish agent-toolkit to npm
    runs-on: ubuntu-latest
    environment: npm

    defaults:
      run:
        working-directory: ./tools/typescript

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm run test

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  pypi-release:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi

    defaults:
      run:
        working-directory: ./tools/python

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Build
        run: |
          set -x
          make venv
          source .venv/bin/activate
          rm -rf build dist *.egg-info
          make build
          python -m twine check dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/python/dist/
